-- CreateEnum
CREATE TYPE "OrigenPagoCompra" AS ENUM ('EFECTIVO_CAJA', 'TRANSFERENCIA_BANCARIA', 'CUENTA_CORRIENTE_PROVEEDOR', 'FONDOS_EXTERNOS');

-- AlterTable
ALTER TABLE "compras" ADD COLUMN     "origen_pago" "OrigenPagoCompra" NOT NULL DEFAULT 'EFECTIVO_CAJA';
